# Generated by Django 3.1.12 on 2026-07-10 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Asistencia',
        ),
        migrations.AlterModelOptions(
            name='estudiante',
            options={},
        ),
        migrations.AlterModelOptions(
            name='inscripcion',
            options={},
        ),
    ]
