# Generated by Django 6.0.6 on 2026-06-18 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id_asistencia', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
                ('justificacion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'asistencia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id_estudiante', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=100, unique=True)),
                ('contrasenia', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'estudiante',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id_inscripcion', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('id_estudiante', models.IntegerField(blank=True, null=True)),
                ('id_clase', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'inscripcion',
                'managed': False,
            },
        ),
    ]
